language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=srcds

after_success:
  - coveralls
